# Aider Configuration File
# This file contains persistent settings for Aider AI coding assistant
# Place this in your home directory (~/.aider.conf.yml) or project root

# Model Configuration
# Uncomment and set your preferred model, or use --model flag
# model: ollama/qwen2.5-coder:latest
# model: gemini/gemini-2.0-flash-exp
# model: openrouter/anthropic/claude-3.5-sonnet
# model: openai/gpt-4

# Editor Model (for smaller edits) - uncomment if needed
# editor-model: ollama/qwen2.5-coder:7b
# editor-model: gemini/gemini-2.0-flash-exp

# Git Integration
auto-commits: true
commit-prompt: true
dirty-commits: true

# Code Editing Preferences
edit-format: diff
pretty: true
stream: true

# File Management
auto-lint: true
lint-cmd: "ruff check"

# Chat Settings
show-diffs: true
show-repo-map: true
show-model-warnings: true

# Performance
map-tokens: 1024
env-file: .env

# Voice Settings (optional)
# voice-language: en

# Cache Settings
cache-prompts: true

# Test Command
test-cmd: "pytest"

# Additional Settings
verbose: false
message-file: .aider.chat.history.md
